import json
import urllib.request
import urllib.parse
import uuid
import os
import websocket
from . import config

def build_sdxl_workflow(prompt_text, negative_text, output_prefix="manhwa_panel"):
    """Generates a standard headless ComfyUI SDXL prompt graph"""
    prompt_id = str(uuid.uuid4())
    workflow = {
        "3": {
            "inputs": {
                "seed": int(uuid.uuid4().int % 1000000000),
                "steps": 25,
                "cfg": 7.0,
                "sampler_name": "euler_ancestral",
                "scheduler": "karras",
                "denoise": 1,
                "model": ["4", 0],
                "positive": ["6", 0],
                "negative": ["7", 0],
                "latent_image": ["5", 0]
            },
            "class_type": "KSampler"
        },
        "4": {
            "inputs": {
                "ckpt_name": config.CHECKPOINT_NAME
            },
            "class_type": "CheckpointLoaderSimple"
        },
        "5": {
            "inputs": {
                "width": 832,
                "height": 1216,
                "batch_size": 1
            },
            "class_type": "EmptyLatentImage"
        },
        "6": {
            "inputs": {
                "text": f"masterpiece, best quality, {prompt_text}",
                "clip": ["4", 1]
            },
            "class_type": "CLIPTextEncode"
        },
        "7": {
            "inputs": {
                "text": f"low quality, worst quality, deformed, bad hands, {negative_text}",
                "clip": ["4", 1]
            },
            "class_type": "CLIPTextEncode"
        },
        "8": {
            "inputs": {
                "samples": ["3", 0],
                "vae": ["4", 2]
            },
            "class_type": "VAEDecode"
        },
        "9": {
            "inputs": {
                "filename_prefix": output_prefix,
                "images": ["8", 0]
            },
            "class_type": "SaveImage"
        }
    }
    return workflow

def queue_prompt(prompt_workflow, client_id):
    payload = json.dumps({"prompt": prompt_workflow, "client_id": client_id}).encode('utf-8')
    req = urllib.request.Request(f"{config.COMFYUI_HOST}/prompt", data=payload, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read())

def download_image(filename, subfolder, folder_type, dest_path):
    params = urllib.parse.urlencode({"filename": filename, "subfolder": subfolder, "type": folder_type})
    url = f"{config.COMFYUI_HOST}/view?{params}"
    urllib.request.urlretrieve(url, dest_path)

def generate_panel(prompt_text, negative_text, output_path):
    """Sync call to ComfyUI to render a panel image"""
    client_id = str(uuid.uuid4())
    workflow = build_sdxl_workflow(prompt_text, negative_text)
    
    prompt_res = queue_prompt(workflow, client_id)
    prompt_id = prompt_res.get('prompt_id')
    print(f"Queued ComfyUI prompt {prompt_id}, awaiting execution...")
    
    ws_url = f"{config.COMFYUI_WS}?clientId={client_id}"
    ws = websocket.create_connection(ws_url)
    
    output_filename = None
    output_subfolder = ""
    output_type = "output"
    
    while True:
        out = ws.recv()
        if isinstance(out, str):
            message = json.loads(out)
            msg_type = message.get('type')
            data = message.get('data', {})
            
            if msg_type == 'status':
                pass
            elif msg_type == 'executing':
                if data.get('node') is None and data.get('prompt_id') == prompt_id:
                    print("Execution finished!")
                    break
            elif msg_type == 'executed':
                if data.get('prompt_id') == prompt_id:
                    output_images = data.get('output', {}).get('images', [])
                    if output_images:
                        output_filename = output_images[0].get('filename')
                        output_subfolder = output_images[0].get('subfolder', '')
                        output_type = output_images[0].get('type', 'output')
        else:
            continue
            
    ws.close()
    
    if output_filename:
        download_image(output_filename, output_subfolder, output_type, output_path)
        print(f"Panel downloaded to {output_path}")
        return output_path
    else:
        raise RuntimeError("No image output generated by ComfyUI")
